# Routes

_home:
    path: ''
    controller: 'HomeController'
    action: 'run'

_releases:
    path: 'releases'
    controller: 'ReleasesController'
    action: 'run'

_doc:
    path: 'doc/(:version)/(:doc)'
    controller: 'HomeController'
    action: 'doc'
    filters:
        require:
            version: '\d\.\d\.\d[\w]{0,1}|[\w-]+"'
            doc: '[\w-]+'
        default:
            version: false
            doc: false