# Routes

_home:
    path:   ''
    controller: 'HomeController'
    action: 'run'

_doc:
    path: 'doc/(:doc)/(:version)'
    controller: 'HomeController'
    action: 'doc'
    filters:
        require:
            doc: '[\w-]+'
            version: '\d\.\d\.\d[\w]*'
        default:
            doc: 'required'