# Routes

_home:
    path:   ''
    controller: 'HomeController'
    action: 'run'

_doc:
    path: 'doc/(:version)/(:doc)'
    controller: 'HomeController'
    action: 'doc'
    filters:
        require:
            version: '\d\.\d\.\d[\w]{0,1}'
            doc: '[\w-]+'
        default:
            version: false
            doc: 'required'