# Routes

_home:
    path:   ''
    controller: 'HomeController'
    action: 'run'

_doc:
    path: 'doc/(:doc)'
    controller: 'HomeController'
    action: 'doc'
    filters:
        require:
            doc: '[\w-]+'
        default:
            doc: 'required'